### ISSUE TITLE
kota

### ISSUE THREAD

**Issue by felixhartono** [opencart-id/select-city#4]
Pagi bos bogalakon,
saya sudah install semuanya dgn benar, database city nya juga ada. 
namun kota nya masih berupa text field. bagaimana agar jadi combo box ya?

tks
![23](https://f.cloud.github.com/assets/5266556/990909/c347bf78-0947-11e3-9790-b510cf5f4fbf.png)

**Comment by bogalakon** [comment]
Install VQmod.

**Comment by felixhartono** [comment]
udah bos.
OC 1.5.6
baru upgrade VQmod 2.4.1

ttp ga bisa. ada masukan lain?

**Comment by bogalakon** [comment]
Saya sudah tes di OC 1.5.6 dan VQmod 2.4.1 (fresh install) dan sukses.

Itu 100% masalahnya ada di vqmod, coba cek error log vqmod-nya.
Jangan lupa upload `select-city.xml` ke folder `/vqmod/xml/`, selebihnya mungkin bisa dilanjutkan di [forum](http://opencart-id.com/showthread.php?tid=788).
