### ISSUE TITLE
ZipCode connect

### ISSUE THREAD

**Issue by jurpro** [opencart-id/select-city#5]
Mas Bogalakon, Bisa gak kolom isian Kode Pos dikaitkan juga dengan City maupun Provinsi. Kolom kode pos ini bisa digunakan untuk memilih kecamatan lengkap dengan Kode pos nya.
Contoh: 
Negara / Country : Indonesia
Province / State : Jawa Barat
City : Bandung
ZipCode / Kode Pos : Kec. Antapani, 40291

Kira-kira seperti itu arah penulisannya. Namun untuk pilihan luar Indonesia bisa diisi sendiri oleh customers.

Makasih ya. Semoga bisa terwujud koneksi ZipCode nya.

Oh iya, jika memilih Negara Indonesia tidak masalah pemilihan City nya. Namun ketika memilih negara lain tidak bisa diisi sendiri oleh customer hanya berupa dropdown saja. Kalau bisa,selain Indonesia bisa menuliskan sendiri oleh customer.

**Comment by bogalakon** [comment]
Emang rencananya itu mau lengkap sampai kecamatan gan jurpro, mungkin saya perlu evaluasi diri dulu kenapa semangat yang dulu membara itu sekarang hilang.
